// This file is auto-generated by @hey-api/openapi-ts

import type { Client, ClientMeta, Options as Options2, RequestResult, TDataShape } from './client';
import { client } from './client.gen';
import type { CreateAcademicYearData, CreateAcademicYearResponses, CreateClassData, CreateClassResponses, CreateStudentData, CreateStudentErrors, CreateStudentResponses, CreateTeacherData, CreateTeacherErrors, CreateTeacherResponses, EnrollStudentData, EnrollStudentResponses, GetAnalyticsOverviewData, GetAnalyticsOverviewErrors, GetAnalyticsOverviewResponses, GetCurrentSchoolProfileData, GetCurrentSchoolProfileResponses, GetSchoolData, GetSchoolErrors, GetSchoolResponses, GetStudentByIdData, GetStudentByIdErrors, GetStudentByIdResponses, ListAcademicYearsData, ListAcademicYearsResponses, ListClassesData, ListClassesResponses, ListEnrollmentsData, ListEnrollmentsResponses, ListOutboxJobsData, ListOutboxJobsResponses, ListStudentsData, ListStudentsErrors, ListStudentsResponses, ListSyncRecordsData, ListSyncRecordsResponses, ListSystemTenantsData, ListSystemTenantsResponses, ListTeachersData, ListTeachersResponses, ListUsersData, ListUsersResponses, LoginData, LoginErrors, LoginResponses, ProvisionTenantData, ProvisionTenantErrors, ProvisionTenantResponses, UpdateCurrentSchoolProfileData, UpdateCurrentSchoolProfileResponses, UpdateStudentData, UpdateStudentErrors, UpdateStudentResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

export const listAcademicYears = <ThrowOnError extends boolean = false>(options?: Options<ListAcademicYearsData, ThrowOnError>): RequestResult<ListAcademicYearsResponses, unknown, ThrowOnError> => (options?.client ?? client).get<ListAcademicYearsResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/academic/academic-years',
    ...options
});

export const createAcademicYear = <ThrowOnError extends boolean = false>(options: Options<CreateAcademicYearData, ThrowOnError>): RequestResult<CreateAcademicYearResponses, unknown, ThrowOnError> => (options.client ?? client).post<CreateAcademicYearResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/academic/academic-years',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const listClasses = <ThrowOnError extends boolean = false>(options?: Options<ListClassesData, ThrowOnError>): RequestResult<ListClassesResponses, unknown, ThrowOnError> => (options?.client ?? client).get<ListClassesResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/academic/classes',
    ...options
});

export const createClass = <ThrowOnError extends boolean = false>(options: Options<CreateClassData, ThrowOnError>): RequestResult<CreateClassResponses, unknown, ThrowOnError> => (options.client ?? client).post<CreateClassResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/academic/classes',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const listEnrollments = <ThrowOnError extends boolean = false>(options?: Options<ListEnrollmentsData, ThrowOnError>): RequestResult<ListEnrollmentsResponses, unknown, ThrowOnError> => (options?.client ?? client).get<ListEnrollmentsResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/academic/enrollments',
    ...options
});

export const enrollStudent = <ThrowOnError extends boolean = false>(options: Options<EnrollStudentData, ThrowOnError>): RequestResult<EnrollStudentResponses, unknown, ThrowOnError> => (options.client ?? client).post<EnrollStudentResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/academic/enrollments',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const getAnalyticsOverview = <ThrowOnError extends boolean = false>(options?: Options<GetAnalyticsOverviewData, ThrowOnError>): RequestResult<GetAnalyticsOverviewResponses, GetAnalyticsOverviewErrors, ThrowOnError> => (options?.client ?? client).get<GetAnalyticsOverviewResponses, GetAnalyticsOverviewErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/analytics/overview',
    ...options
});

/**
 * Authenticate a user and return a JWT access token.
 *
 * This endpoint verifies the user's email and password against the provided tenant.
 * Upon successful verification, it returns an access token valid for 24 hours.
 */
export const login = <ThrowOnError extends boolean = false>(options: Options<LoginData, ThrowOnError>): RequestResult<LoginResponses, LoginErrors, ThrowOnError> => (options.client ?? client).post<LoginResponses, LoginErrors, ThrowOnError>({
    url: '/api/v1/auth/login',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const listUsers = <ThrowOnError extends boolean = false>(options?: Options<ListUsersData, ThrowOnError>): RequestResult<ListUsersResponses, unknown, ThrowOnError> => (options?.client ?? client).get<ListUsersResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/auth/users',
    ...options
});

export const listOutboxJobs = <ThrowOnError extends boolean = false>(options?: Options<ListOutboxJobsData, ThrowOnError>): RequestResult<ListOutboxJobsResponses, unknown, ThrowOnError> => (options?.client ?? client).get<ListOutboxJobsResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/dapodik/outbox-jobs',
    ...options
});

export const listSyncRecords = <ThrowOnError extends boolean = false>(options?: Options<ListSyncRecordsData, ThrowOnError>): RequestResult<ListSyncRecordsResponses, unknown, ThrowOnError> => (options?.client ?? client).get<ListSyncRecordsResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/dapodik/sync-records',
    ...options
});

/**
 * Retrieve current tenant school profile from PostgreSQL database.
 */
export const getCurrentSchoolProfile = <ThrowOnError extends boolean = false>(options?: Options<GetCurrentSchoolProfileData, ThrowOnError>): RequestResult<GetCurrentSchoolProfileResponses, unknown, ThrowOnError> => (options?.client ?? client).get<GetCurrentSchoolProfileResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/schools/profile',
    ...options
});

/**
 * Update current tenant school profile & dynamic logo in PostgreSQL database.
 */
export const updateCurrentSchoolProfile = <ThrowOnError extends boolean = false>(options: Options<UpdateCurrentSchoolProfileData, ThrowOnError>): RequestResult<UpdateCurrentSchoolProfileResponses, unknown, ThrowOnError> => (options.client ?? client).put<UpdateCurrentSchoolProfileResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/schools/profile',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Retrieve school details by ID.
 */
export const getSchool = <ThrowOnError extends boolean = false>(options: Options<GetSchoolData, ThrowOnError>): RequestResult<GetSchoolResponses, GetSchoolErrors, ThrowOnError> => (options.client ?? client).get<GetSchoolResponses, GetSchoolErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/schools/{id}',
    ...options
});

/**
 * Retrieve a paginated list of Students.
 *
 * Supports filtering by search, grade_level, class_id, status, and date range.
 */
export const listStudents = <ThrowOnError extends boolean = false>(options?: Options<ListStudentsData, ThrowOnError>): RequestResult<ListStudentsResponses, ListStudentsErrors, ThrowOnError> => (options?.client ?? client).get<ListStudentsResponses, ListStudentsErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/students',
    ...options
});

/**
 * Create a new Student.
 *
 * Requires an `Idempotency-Key` header to prevent duplicate registration.
 */
export const createStudent = <ThrowOnError extends boolean = false>(options: Options<CreateStudentData, ThrowOnError>): RequestResult<CreateStudentResponses, CreateStudentErrors, ThrowOnError> => (options.client ?? client).post<CreateStudentResponses, CreateStudentErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/students',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Retrieve a Student by ID.
 */
export const getStudentById = <ThrowOnError extends boolean = false>(options: Options<GetStudentByIdData, ThrowOnError>): RequestResult<GetStudentByIdResponses, GetStudentByIdErrors, ThrowOnError> => (options.client ?? client).get<GetStudentByIdResponses, GetStudentByIdErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/students/{id}',
    ...options
});

/**
 * Update a Student by ID.
 */
export const updateStudent = <ThrowOnError extends boolean = false>(options: Options<UpdateStudentData, ThrowOnError>): RequestResult<UpdateStudentResponses, UpdateStudentErrors, ThrowOnError> => (options.client ?? client).patch<UpdateStudentResponses, UpdateStudentErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/students/{id}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * List all tenants and schools for system administration
 */
export const listSystemTenants = <ThrowOnError extends boolean = false>(options?: Options<ListSystemTenantsData, ThrowOnError>): RequestResult<ListSystemTenantsResponses, unknown, ThrowOnError> => (options?.client ?? client).get<ListSystemTenantsResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/system/tenants',
    ...options
});

export const listTeachers = <ThrowOnError extends boolean = false>(options?: Options<ListTeachersData, ThrowOnError>): RequestResult<ListTeachersResponses, unknown, ThrowOnError> => (options?.client ?? client).get<ListTeachersResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/teachers',
    ...options
});

export const createTeacher = <ThrowOnError extends boolean = false>(options: Options<CreateTeacherData, ThrowOnError>): RequestResult<CreateTeacherResponses, CreateTeacherErrors, ThrowOnError> => (options.client ?? client).post<CreateTeacherResponses, CreateTeacherErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/teachers',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Provision a new Tenant and its associated School.
 *
 * Requires an `Idempotency-Key` header to prevent duplicate provisioning.
 */
export const provisionTenant = <ThrowOnError extends boolean = false>(options: Options<ProvisionTenantData, ThrowOnError>): RequestResult<ProvisionTenantResponses, ProvisionTenantErrors, ThrowOnError> => (options.client ?? client).post<ProvisionTenantResponses, ProvisionTenantErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/tenants/provision',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});
