// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://openapi.json` | (string & {});
};

export type AcademicYearResponse = {
    end_date: string;
    id: string;
    is_active: boolean;
    name: string;
    start_date: string;
};

export type ActivateMasterRequest = {
    email: string;
    full_name: string;
    password: string;
    role_name?: string | null;
};

export type ActivateMasterResponse = {
    assigned_role: string;
    email: string;
    full_name: string;
    message: string;
    user_id: string;
};

export type AnalyticsOverviewResponse = {
    active_classes: number;
    active_students: number;
    at_risk_students: number;
    attendance_rate: number;
    total_classes: number;
    total_guardians: number;
    total_students: number;
    total_teachers: number;
    total_tendik: number;
};

export type ApiErrorDetail = {
    code: string;
    correlation_id: string;
    details?: {
        [key: string]: unknown;
    } | null;
    message: string;
    trace_id: string;
};

export type ApiMeta = {
    cursor?: string | null;
    execution_time_ms?: number | null;
    next_cursor?: string | null;
    pagination?: null | PaginationMeta;
};

export type ApiResponseAcademicYearResponse = {
    data?: {
        end_date: string;
        id: string;
        is_active: boolean;
        name: string;
        start_date: string;
    };
    error?: null | ApiErrorDetail;
    meta?: null | ApiMeta;
    request_id: string;
    success: boolean;
    timestamp: string;
    version: string;
};

export type ApiResponseAnalyticsOverviewResponse = {
    data?: {
        active_classes: number;
        active_students: number;
        at_risk_students: number;
        attendance_rate: number;
        total_classes: number;
        total_guardians: number;
        total_students: number;
        total_teachers: number;
        total_tendik: number;
    };
    error?: null | ApiErrorDetail;
    meta?: null | ApiMeta;
    request_id: string;
    success: boolean;
    timestamp: string;
    version: string;
};

export type ApiResponseClassResponse = {
    data?: {
        academic_year_id: string;
        grade_level_id: string;
        homeroom_teacher_id?: string | null;
        id: string;
        name: string;
    };
    error?: null | ApiErrorDetail;
    meta?: null | ApiMeta;
    request_id: string;
    success: boolean;
    timestamp: string;
    version: string;
};

export type ApiResponseEnrollmentResponse = {
    data?: {
        academic_year_id: string;
        class_id: string;
        id: string;
        is_active: boolean;
        student_id: string;
    };
    error?: null | ApiErrorDetail;
    meta?: null | ApiMeta;
    request_id: string;
    success: boolean;
    timestamp: string;
    version: string;
};

export type ApiResponseVecAcademicYearResponse = {
    data?: Array<{
        end_date: string;
        id: string;
        is_active: boolean;
        name: string;
        start_date: string;
    }>;
    error?: null | ApiErrorDetail;
    meta?: null | ApiMeta;
    request_id: string;
    success: boolean;
    timestamp: string;
    version: string;
};

export type ApiResponseVecClassResponse = {
    data?: Array<{
        academic_year_id: string;
        grade_level_id: string;
        homeroom_teacher_id?: string | null;
        id: string;
        name: string;
    }>;
    error?: null | ApiErrorDetail;
    meta?: null | ApiMeta;
    request_id: string;
    success: boolean;
    timestamp: string;
    version: string;
};

export type ApiResponseVecEnrollmentResponse = {
    data?: Array<{
        academic_year_id: string;
        class_id: string;
        id: string;
        is_active: boolean;
        student_id: string;
    }>;
    error?: null | ApiErrorDetail;
    meta?: null | ApiMeta;
    request_id: string;
    success: boolean;
    timestamp: string;
    version: string;
};

export type AuthUserDto = {
    created_at: string;
    email: string;
    full_name: string;
    id: string;
    is_active: boolean;
    role: string;
};

export type ClassResponse = {
    academic_year_id: string;
    grade_level_id: string;
    homeroom_teacher_id?: string | null;
    id: string;
    name: string;
};

export type CreateAcademicYearRequest = {
    end_date: string;
    name: string;
    start_date: string;
};

export type CreateClassRequest = {
    academic_year_id: string;
    grade_level_id: string;
    name: string;
};

export type CreateStudentRequest = {
    date_of_birth?: string | null;
    full_name: string;
    gender?: string | null;
    guardian_id?: string | null;
    nik?: string | null;
    nisn: string;
    place_of_birth?: string | null;
    religion?: string | null;
};

export type CreateTeacherRequest = {
    full_name: string;
    nip?: string | null;
};

export type DapodikOutboxJobDto = {
    attempts: number;
    created_at: string;
    entity_id: string;
    idempotency_key: string;
    job_id: string;
    operation: string;
    req_id: string;
    status: string;
};

export type DapodikSyncRecordDto = {
    action_recommended: string;
    classification: string;
    id: string;
    identity_state: string;
    last_synced_at: string;
    mobility_case: string;
    nama_dapodik: string;
    nama_school_os: string;
    nik: string;
    nisn: string;
    rombel: string;
    stage: string;
};

export type EnrollStudentRequest = {
    class_id: string;
    student_id: string;
};

export type EnrollmentResponse = {
    academic_year_id: string;
    class_id: string;
    id: string;
    is_active: boolean;
    student_id: string;
};

export type LoginRequest = {
    email?: string | null;
    password: string;
    username?: string | null;
};

export type LoginResponse = {
    access_token: string;
    expires_in: number;
    token_type: string;
};

export type PaginationMeta = {
    page: number;
    page_size: number;
    total_items: number;
    total_pages: number;
};

export type ProvisionTenantRequest = {
    school_name: string;
    tenant_name: string;
};

export type ProvisionTenantResponse = {
    message: string;
    tenant_id: string;
};

export type SchoolResponse = {
    accreditation?: string | null;
    address?: string | null;
    created_at: string;
    email?: string | null;
    id: string;
    logo_url?: string | null;
    name: string;
    npsn?: string | null;
    phone_number?: string | null;
    status: string;
    tenant_id: string;
    updated_at: string;
};

export type StudentResponse = {
    alamat_jalan?: string | null;
    class_name?: string | null;
    created_at: string;
    date_of_birth?: string | null;
    email?: string | null;
    full_name: string;
    gender?: string | null;
    guardian_id?: string | null;
    id: string;
    nik?: string | null;
    nipd?: string | null;
    nisn: string;
    no_hp?: string | null;
    place_of_birth?: string | null;
    religion?: string | null;
    status: string;
    tenant_id: string;
    updated_at: string;
    user_id?: string | null;
};

export type TeacherResponse = {
    agama?: string | null;
    alamat_jalan?: string | null;
    created_at: string;
    email?: string | null;
    full_name: string;
    id: string;
    is_active: boolean;
    jenis_ptk?: string | null;
    jk?: string | null;
    nip?: string | null;
    no_hp?: string | null;
    nuptk?: string | null;
    status_kepegawaian?: string | null;
    subject?: string | null;
    tanggal_lahir?: string | null;
    tempat_lahir?: string | null;
    tenant_id: string;
    updated_at: string;
    user_id?: string | null;
};

export type TenantSummaryResponse = {
    created_at: string;
    is_active: boolean;
    school_name?: string | null;
    server_status: string;
    tenant_id: string;
    tenant_name: string;
};

export type UpdateSchoolRequest = {
    accreditation?: string | null;
    address?: string | null;
    email?: string | null;
    logo_url?: string | null;
    name?: string | null;
    npsn?: string | null;
    phone_number?: string | null;
    status?: string | null;
};

export type UpdateStudentRequest = {
    date_of_birth?: string | null;
    full_name?: string | null;
    gender?: string | null;
    nik?: string | null;
    nisn?: string | null;
    place_of_birth?: string | null;
    religion?: string | null;
};

export type ListAcademicYearsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Page number
         */
        page?: number;
        /**
         * Items per page
         */
        page_size?: number;
    };
    url: '/api/v1/academic/academic-years';
};

export type ListAcademicYearsResponses = {
    /**
     * List of Academic Years
     */
    200: ApiResponseVecAcademicYearResponse;
};

export type ListAcademicYearsResponse = ListAcademicYearsResponses[keyof ListAcademicYearsResponses];

export type CreateAcademicYearData = {
    body: CreateAcademicYearRequest;
    path?: never;
    query?: never;
    url: '/api/v1/academic/academic-years';
};

export type CreateAcademicYearResponses = {
    /**
     * Academic Year created
     */
    201: ApiResponseAcademicYearResponse;
};

export type CreateAcademicYearResponse = CreateAcademicYearResponses[keyof CreateAcademicYearResponses];

export type ListClassesData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Filter by academic year
         */
        academic_year_id?: string;
        /**
         * Page number
         */
        page?: number;
        /**
         * Items per page
         */
        page_size?: number;
    };
    url: '/api/v1/academic/classes';
};

export type ListClassesResponses = {
    /**
     * List of Classes
     */
    200: ApiResponseVecClassResponse;
};

export type ListClassesResponse = ListClassesResponses[keyof ListClassesResponses];

export type CreateClassData = {
    body: CreateClassRequest;
    path?: never;
    query?: never;
    url: '/api/v1/academic/classes';
};

export type CreateClassResponses = {
    /**
     * Class created
     */
    201: ApiResponseClassResponse;
};

export type CreateClassResponse = CreateClassResponses[keyof CreateClassResponses];

export type ListEnrollmentsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Filter by academic year
         */
        academic_year_id?: string;
        /**
         * Filter by class
         */
        class_id?: string;
        /**
         * Filter by student
         */
        student_id?: string;
        /**
         * Page number
         */
        page?: number;
        /**
         * Items per page
         */
        page_size?: number;
    };
    url: '/api/v1/academic/enrollments';
};

export type ListEnrollmentsResponses = {
    /**
     * List of Enrollments
     */
    200: ApiResponseVecEnrollmentResponse;
};

export type ListEnrollmentsResponse = ListEnrollmentsResponses[keyof ListEnrollmentsResponses];

export type EnrollStudentData = {
    body: EnrollStudentRequest;
    path?: never;
    query?: never;
    url: '/api/v1/academic/enrollments';
};

export type EnrollStudentResponses = {
    /**
     * Student enrolled
     */
    201: ApiResponseEnrollmentResponse;
};

export type EnrollStudentResponse = EnrollStudentResponses[keyof EnrollStudentResponses];

export type GetAnalyticsOverviewData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/analytics/overview';
};

export type GetAnalyticsOverviewErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
};

export type GetAnalyticsOverviewResponses = {
    /**
     * Analytics Overview
     */
    200: ApiResponseAnalyticsOverviewResponse;
};

export type GetAnalyticsOverviewResponse = GetAnalyticsOverviewResponses[keyof GetAnalyticsOverviewResponses];

export type LoginData = {
    body: LoginRequest;
    path?: never;
    query?: never;
    url: '/api/v1/auth/login';
};

export type LoginErrors = {
    /**
     * Invalid credentials
     */
    401: unknown;
    /**
     * Missing tenant ID
     */
    403: unknown;
};

export type LoginResponses = {
    /**
     * Login successful
     */
    200: {
        data?: {
            access_token: string;
            expires_in: number;
            token_type: string;
        };
        error?: null | ApiErrorDetail;
        meta?: null | ApiMeta;
        request_id: string;
        success: boolean;
        timestamp: string;
        version: string;
    };
};

export type LoginResponse2 = LoginResponses[keyof LoginResponses];

export type ListUsersData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/auth/users';
};

export type ListUsersResponses = {
    /**
     * Users listed successfully
     */
    200: {
        data?: Array<{
            created_at: string;
            email: string;
            full_name: string;
            id: string;
            is_active: boolean;
            role: string;
        }>;
        error?: null | ApiErrorDetail;
        meta?: null | ApiMeta;
        request_id: string;
        success: boolean;
        timestamp: string;
        version: string;
    };
};

export type ListUsersResponse = ListUsersResponses[keyof ListUsersResponses];

export type ListOutboxJobsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/dapodik/outbox-jobs';
};

export type ListOutboxJobsResponses = {
    /**
     * List outbox queue jobs from PostgreSQL
     */
    200: unknown;
};

export type ListSyncRecordsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/dapodik/sync-records';
};

export type ListSyncRecordsResponses = {
    /**
     * List differential matrix sync records from PostgreSQL
     */
    200: unknown;
};

export type GetCurrentSchoolProfileData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/schools/profile';
};

export type GetCurrentSchoolProfileResponses = {
    /**
     * School profile retrieved successfully
     */
    200: {
        data?: {
            accreditation?: string | null;
            address?: string | null;
            created_at: string;
            email?: string | null;
            id: string;
            logo_url?: string | null;
            name: string;
            npsn?: string | null;
            phone_number?: string | null;
            status: string;
            tenant_id: string;
            updated_at: string;
        };
        error?: null | ApiErrorDetail;
        meta?: null | ApiMeta;
        request_id: string;
        success: boolean;
        timestamp: string;
        version: string;
    };
};

export type GetCurrentSchoolProfileResponse = GetCurrentSchoolProfileResponses[keyof GetCurrentSchoolProfileResponses];

export type UpdateCurrentSchoolProfileData = {
    body: UpdateSchoolRequest;
    path?: never;
    query?: never;
    url: '/api/v1/schools/profile';
};

export type UpdateCurrentSchoolProfileResponses = {
    /**
     * School profile updated successfully in PostgreSQL
     */
    200: {
        data?: {
            accreditation?: string | null;
            address?: string | null;
            created_at: string;
            email?: string | null;
            id: string;
            logo_url?: string | null;
            name: string;
            npsn?: string | null;
            phone_number?: string | null;
            status: string;
            tenant_id: string;
            updated_at: string;
        };
        error?: null | ApiErrorDetail;
        meta?: null | ApiMeta;
        request_id: string;
        success: boolean;
        timestamp: string;
        version: string;
    };
};

export type UpdateCurrentSchoolProfileResponse = UpdateCurrentSchoolProfileResponses[keyof UpdateCurrentSchoolProfileResponses];

export type GetSchoolData = {
    body?: never;
    path: {
        /**
         * School UUID
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/schools/{id}';
};

export type GetSchoolErrors = {
    /**
     * School not found
     */
    404: unknown;
};

export type GetSchoolResponses = {
    /**
     * School retrieved successfully
     */
    200: {
        data?: {
            accreditation?: string | null;
            address?: string | null;
            created_at: string;
            email?: string | null;
            id: string;
            logo_url?: string | null;
            name: string;
            npsn?: string | null;
            phone_number?: string | null;
            status: string;
            tenant_id: string;
            updated_at: string;
        };
        error?: null | ApiErrorDetail;
        meta?: null | ApiMeta;
        request_id: string;
        success: boolean;
        timestamp: string;
        version: string;
    };
};

export type GetSchoolResponse = GetSchoolResponses[keyof GetSchoolResponses];

export type ListStudentsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Page number (1-indexed)
         */
        page?: number;
        /**
         * Number of items per page
         */
        page_size?: number;
        /**
         * Search query by name
         */
        search?: string;
        /**
         * Filter by grade level UUID
         */
        grade_level_id?: string;
        /**
         * Filter by class ID
         */
        class_id?: string;
        /**
         * Filter by status (active/inactive)
         */
        status?: string;
        /**
         * Filter records created on or after this date
         */
        created_at_from?: string;
        /**
         * Filter records created on or before this date
         */
        created_at_to?: string;
    };
    url: '/api/v1/students';
};

export type ListStudentsErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
};

export type ListStudentsResponses = {
    /**
     * Students retrieved successfully
     */
    200: {
        data?: Array<{
            alamat_jalan?: string | null;
            class_name?: string | null;
            date_of_birth?: string | null;
            email?: string | null;
            full_name: string;
            gender?: string | null;
            grade?: string | null;
            id: string;
            nik?: string | null;
            nipd?: string | null;
            nisn: string;
            no_hp?: string | null;
            place_of_birth?: string | null;
            religion?: string | null;
            status: string;
            updated_at: string;
        }>;
        error?: null | ApiErrorDetail;
        meta?: null | ApiMeta;
        request_id: string;
        success: boolean;
        timestamp: string;
        version: string;
    };
};

export type ListStudentsResponse = ListStudentsResponses[keyof ListStudentsResponses];

export type CreateStudentData = {
    body: CreateStudentRequest;
    path?: never;
    query?: never;
    url: '/api/v1/students';
};

export type CreateStudentErrors = {
    /**
     * Idempotency key missing or invalid
     */
    400: unknown;
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Permission Denied
     */
    403: unknown;
};

export type CreateStudentResponses = {
    /**
     * Student created successfully
     */
    201: {
        data?: {
            alamat_jalan?: string | null;
            class_name?: string | null;
            created_at: string;
            date_of_birth?: string | null;
            email?: string | null;
            full_name: string;
            gender?: string | null;
            guardian_id?: string | null;
            id: string;
            nik?: string | null;
            nipd?: string | null;
            nisn: string;
            no_hp?: string | null;
            place_of_birth?: string | null;
            religion?: string | null;
            status: string;
            tenant_id: string;
            updated_at: string;
            user_id?: string | null;
        };
        error?: null | ApiErrorDetail;
        meta?: null | ApiMeta;
        request_id: string;
        success: boolean;
        timestamp: string;
        version: string;
    };
};

export type CreateStudentResponse = CreateStudentResponses[keyof CreateStudentResponses];

export type GetStudentByIdData = {
    body?: never;
    path: {
        /**
         * Student UUID
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/students/{id}';
};

export type GetStudentByIdErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Student not found
     */
    404: unknown;
};

export type GetStudentByIdResponses = {
    /**
     * Student retrieved successfully
     */
    200: {
        data?: {
            academic_year?: {
                [key: string]: unknown;
            } | null;
            alamat_jalan?: string | null;
            attendance_summary?: {
                [key: string]: unknown;
            } | null;
            class_name?: string | null;
            created_at: string;
            current_class?: {
                [key: string]: unknown;
            } | null;
            current_enrollment?: {
                [key: string]: unknown;
            } | null;
            date_of_birth?: string | null;
            email?: string | null;
            full_name: string;
            gender?: string | null;
            grade?: string | null;
            guardian?: {
                [key: string]: unknown;
            } | null;
            guardian_id?: string | null;
            id: string;
            latest_assessment_summary?: {
                [key: string]: unknown;
            } | null;
            nik?: string | null;
            nipd?: string | null;
            nisn: string;
            no_hp?: string | null;
            place_of_birth?: string | null;
            religion?: string | null;
            status: string;
            tenant_id: string;
            updated_at: string;
            user_id?: string | null;
        };
        error?: null | ApiErrorDetail;
        meta?: null | ApiMeta;
        request_id: string;
        success: boolean;
        timestamp: string;
        version: string;
    };
};

export type GetStudentByIdResponse = GetStudentByIdResponses[keyof GetStudentByIdResponses];

export type UpdateStudentData = {
    body: UpdateStudentRequest;
    path: {
        /**
         * Student UUID
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/students/{id}';
};

export type UpdateStudentErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Student not found
     */
    404: unknown;
};

export type UpdateStudentResponses = {
    /**
     * Student updated successfully
     */
    200: {
        data?: {
            alamat_jalan?: string | null;
            class_name?: string | null;
            created_at: string;
            date_of_birth?: string | null;
            email?: string | null;
            full_name: string;
            gender?: string | null;
            guardian_id?: string | null;
            id: string;
            nik?: string | null;
            nipd?: string | null;
            nisn: string;
            no_hp?: string | null;
            place_of_birth?: string | null;
            religion?: string | null;
            status: string;
            tenant_id: string;
            updated_at: string;
            user_id?: string | null;
        };
        error?: null | ApiErrorDetail;
        meta?: null | ApiMeta;
        request_id: string;
        success: boolean;
        timestamp: string;
        version: string;
    };
};

export type UpdateStudentResponse = UpdateStudentResponses[keyof UpdateStudentResponses];

export type ListSystemTenantsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/system/tenants';
};

export type ListSystemTenantsResponses = {
    /**
     * Successfully listed tenants
     */
    200: {
        data?: Array<{
            created_at: string;
            is_active: boolean;
            school_name?: string | null;
            server_status: string;
            tenant_id: string;
            tenant_name: string;
        }>;
        error?: null | ApiErrorDetail;
        meta?: null | ApiMeta;
        request_id: string;
        success: boolean;
        timestamp: string;
        version: string;
    };
};

export type ListSystemTenantsResponse = ListSystemTenantsResponses[keyof ListSystemTenantsResponses];

export type ListTeachersData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Page number
         */
        page?: number;
        /**
         * Items per page
         */
        page_size?: number;
        /**
         * Search by name or NIP
         */
        search?: string;
    };
    url: '/api/v1/teachers';
};

export type ListTeachersResponses = {
    /**
     * List of teachers
     */
    200: {
        data?: Array<{
            agama?: string | null;
            alamat_jalan?: string | null;
            created_at: string;
            email?: string | null;
            full_name: string;
            id: string;
            is_active: boolean;
            jenis_ptk?: string | null;
            jk?: string | null;
            nip?: string | null;
            no_hp?: string | null;
            nuptk?: string | null;
            status_kepegawaian?: string | null;
            subject?: string | null;
            tanggal_lahir?: string | null;
            tempat_lahir?: string | null;
            tenant_id: string;
            updated_at: string;
            user_id?: string | null;
        }>;
        error?: null | ApiErrorDetail;
        meta?: null | ApiMeta;
        request_id: string;
        success: boolean;
        timestamp: string;
        version: string;
    };
};

export type ListTeachersResponse = ListTeachersResponses[keyof ListTeachersResponses];

export type CreateTeacherData = {
    body: CreateTeacherRequest;
    path?: never;
    query?: never;
    url: '/api/v1/teachers';
};

export type CreateTeacherErrors = {
    /**
     * Unauthorized
     */
    401: ApiErrorDetail;
};

export type CreateTeacherError = CreateTeacherErrors[keyof CreateTeacherErrors];

export type CreateTeacherResponses = {
    /**
     * Teacher created successfully
     */
    200: {
        data?: {
            agama?: string | null;
            alamat_jalan?: string | null;
            created_at: string;
            email?: string | null;
            full_name: string;
            id: string;
            is_active: boolean;
            jenis_ptk?: string | null;
            jk?: string | null;
            nip?: string | null;
            no_hp?: string | null;
            nuptk?: string | null;
            status_kepegawaian?: string | null;
            subject?: string | null;
            tanggal_lahir?: string | null;
            tempat_lahir?: string | null;
            tenant_id: string;
            updated_at: string;
            user_id?: string | null;
        };
        error?: null | ApiErrorDetail;
        meta?: null | ApiMeta;
        request_id: string;
        success: boolean;
        timestamp: string;
        version: string;
    };
};

export type CreateTeacherResponse = CreateTeacherResponses[keyof CreateTeacherResponses];

export type ProvisionTenantData = {
    body: ProvisionTenantRequest;
    path?: never;
    query?: never;
    url: '/api/v1/tenants/provision';
};

export type ProvisionTenantErrors = {
    /**
     * Idempotency key missing or invalid
     */
    400: unknown;
};

export type ProvisionTenantResponses = {
    /**
     * Provisioning successful
     */
    200: {
        data?: {
            message: string;
            tenant_id: string;
        };
        error?: null | ApiErrorDetail;
        meta?: null | ApiMeta;
        request_id: string;
        success: boolean;
        timestamp: string;
        version: string;
    };
};

export type ProvisionTenantResponse2 = ProvisionTenantResponses[keyof ProvisionTenantResponses];
